### ISSUE TITLE
Matching task-todo: cant pull immediate headers

### ISSUE THREAD

**Issue by QuaCKeReD** [mrjackphil/obsidian-text-expand#43]
Trying to pull all task-todo: from a list of files, along with their immediate '#' header values;

code:
```expander
(task-todo:"") (file:"ToDo test")
$filename
$header:#
$match
```
expected output;
`ToDo test 1
[[ToDo test 1#Heading 1]]
- [ ] task under heading 1
- [ ] another task under heading 1
[[ToDo test 1#Heading 2]]
- [ ] task under heading 2
[[ToDo test 1#Heading 3]]
- [ ] task under heading 3`

actual output;
`ToDo test 1
[[ToDo test 1#Heading 1]]
[[ToDo test 1#Heading 2]]
[[ToDo test 1#Heading 3]]
- [ ] task under heading 1
- [ ] another task under heading 1
- [ ] task under heading 2
- [ ] task under heading 3`

**Comment by mrjackphil** [comment]
@QuaCKeReD thanks for the issue. I'll check when will have some time.
